# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Project
    identifier: proj
    weight: 10
  - name: Study Notes
    url: blog/
    weight: 10
  - name: About
    url: about/
    weight: 10
  - name: Kärger
    parent: proj
    url: projects/karger
    weight: 20
  - name: Richard
    parent: proj
    url: projects/richard
    weight: 20
  - name: Harmonic
    parent: proj
    url: projects/harmonic
    weight: 20
  - name: Hashimoto
    parent: proj
    url: projects/thyoid
    weight: 20