# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Blog
    identifier: blog
    weight: 20
  - name: Projects
    parent: blog
    url: projects/
    weight: 20
  - name: Notes
    parent: blog
    url: blog/
    weight: 20
  - name: About
    url: about/
    weight: 30
